assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    read_from: '%kernel.project_dir%/public'
    write_to: '%kernel.project_dir%/public'
    filters:
        cssrewrite: ~