#liip_imagine:
#    # valid drivers options include "gd" or "gmagick" or "imagick"
#    driver: "gd"
#
#    # define your filter sets under this option
#    filter_sets:
#
#        # an example thumbnail transformation definition
#        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
#        squared_thumbnail:
#
#            # set your image quality defaults
#            jpeg_quality:          85
#            png_compression_level: 8
#
#            # setup the filter steps to apply for this transformation
#            filters:
#
#                # auto rotate the image using EXIF metadata
#                auto_rotate: ~
#
#                # strip the image of all metadata
#                strip: ~
#
#                # scale and square the image to the given dimensions
#                thumbnail:
#                    size:          [253, 253]
#                    mode:          outbound
#                    allow_upscale: true
#
#                # create border by placing image on larger black background
#                background:
#                    size:     [256, 256]
#                    position: center
#                    color:    '#fff'
liip_imagine:
    driver: "gd"

    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public'
#                cache_prefix: ~ # media/cache

    loaders:
        default:
            filesystem:
                data_root: ~  # %kernel.root_dir%/../web/

    cache:                default
    data_loader:          default
    default_image:        null

#    controller:
#        filter_action:         liip_imagine.controller:filterAction
#        filter_runtime_action: liip_imagine.controller:filterRuntimeAction

    filter_sets:
        cache: ~
        relative_resize_quality_100_128:
            quality: 100
            filters:
                relative_resize: { widen: 128 }
        thumbnail_quality_100_128x128_outbound:
                    quality: 100
                    filters:
                        thumbnail: { size: [128, 128], mode: outbound }
        thumbnail_quality_100_22x22_outbound:
            quality: 100
            filters:
                thumbnail: { size: [22, 22], mode: outbound }
        thumbnail_quality_100_90x90_outbound:
            quality: 100
            filters:
                thumbnail: { size: [90, 90], mode: outbound }
        relative_resize_quality_100_400:
            quality: 100
            filters:
                relative_resize: { widen: 400 }