parameters:
   sonata.media.admin.groupname: Content
   sonata.media.provider.image.class: App\ExtendedSonataMediaBundle\Provider\ImageProvider

sonata_media:
    # if you don't use default namespace configuration
    class:
        media: App\ExtendedSonataMediaBundle\Entity\Media
        gallery: App\ExtendedSonataMediaBundle\Entity\Gallery
        gallery_has_media: App\ExtendedSonataMediaBundle\Entity\GalleryHasMedia
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
    default_context: default # you need to set a context
    #providers:
        #image:
          #resizer:    sonata.media.resizer.simple # sonata.media.resizer.square
          #filesystem: sonata.media.filesystem.local
          #cdn:        sonata.media.cdn.server
          #generator:  sonata.media.generator.default
          #thumbnail:  sonata.media.thumbnail.format
          #thumbnail:  sonata.media.thumbnail.liip_imagine

    contexts:
        default:  # the default context is mandatory
            download:
                strategy: sonata.media.security.superadmin_strategy
                mode: http
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo
            formats:
                small: { width: 150 , quality: 100}
                big:   { width: 300 , quality: 100}
        user:
            download:
                strategy: sonata.media.security.superadmin_strategy
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                small: { width: 150, quality: 100}
                big:   { width: 300, quality: 100}
        product:
            download:
                strategy: sonata.media.security.superadmin_strategy
                mode: http
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.youtube
                - sonata.media.provider.file
            formats:
                small: { width: 150, quality: 100}
                big:   { width: 300, quality: 100}
    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  '%kernel.root_dir%/../public/uploads/media'
            create:     false