<?php

namespace App\AppBundle\Repository;

use App\AppBundle\Entity\ProductAttr;
use Doctrine\ORM\QueryBuilder;

/**
 * CatalogAttrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductAttrRepository extends \Doctrine\ORM\EntityRepository
{
}
