<?php

namespace AppBundle\Repository;

/**
 * ProductCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCategoryRepository extends \Gedmo\Tree\Entity\Repository\NestedTreeRepository
{
}
