<?php

namespace AppBundle\Repository;

/**
 * ProductAttrValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductAttrValueRepository extends \Doctrine\ORM\EntityRepository
{
}
