<?php

namespace AppBundle\Repository;

/**
 * CatalogAttrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductAttrRepository extends \Doctrine\ORM\EntityRepository
{
}
