liip_imagine:
    resolvers:
       default:
          web_path:
              web_root: %kernel.root_dir%/../web
              cache_prefix: uploads/cache

    filter_sets:
        cache: ~
        relative_resize_quality_100_128:
            quality: 100
            filters:
                relative_resize: { widen: 128 }
        thumbnail_quality_100_128x128_outbound:
                    quality: 100
                    filters:
                        thumbnail: { size: [128, 128], mode: outbound }
        thumbnail_quality_100_22x22_outbound:
            quality: 100
            filters:
                thumbnail: { size: [22, 22], mode: outbound }
        thumbnail_quality_100_90x90_outbound:
            quality: 100
            filters:
                thumbnail: { size: [90, 90], mode: outbound }
        relative_resize_quality_100_400:
            quality: 100
            filters:
                relative_resize: { widen: 400 }