imports:
    - { resource: sonata_media.yml }
    - { resource: sonata_formatter.yml }
    - { resource: sonata_translation.yml }
    - { resource: '@AppBundle/Resources/config/sonata_admin.yml' }

sonata_admin:
    templates:
        layout: 'AppBundle:Admin:standard_layout.html.twig'
        user_block: 'AppBundle:Admin:Core/user_block.html.twig'
    security:
        handler: sonata.admin.security.handler.role

sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        # ...

#sonata_doctrine_orm_admin:
#    templates:
#        form: []