homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

page:
    path:     /page/{id}
    defaults: { _controller: AppBundle:Pages:index }

products_list:
    path:     /products/{page}/{categoryId}
    defaults: { _controller: AppBundle:Products:index, page: 1, categoryId: null }
