homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

page:
    path:     /page/{id}
    defaults: { _controller: AppBundle:Page:index }

catalog:
    path:     /catalog/{categoryId}/{page}
    defaults: { _controller: AppBundle:Catalog:index, categoryId: 0, page: 1 }
