homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

page:
    path:     /page/{id}
    defaults: { _controller: AppBundle:Page:index }

catalog:
    path:     /catalog/{id}
    defaults: { _controller: AppBundle:Catalog:index, id: 0  }
