parameters:

services:
     fos_user.user_manager:
        class: AppBundle\Managers\UserManager
        public: true
        arguments:
            - '@fos_user.util.password_updater'
            - '@fos_user.util.canonical_fields_updater'
            - '@fos_user.object_manager'
            - AppBundle\Entity\User

     app.twig_extension:
        class: AppBundle\Twig\TwigExtension
        public: false
        arguments:
            - '@service_container'
        tags: [{ name: twig.extension }]

     app.managers.page_manager:
        class: AppBundle\Managers\PageManager
        public: true
        arguments:
           - '@doctrine.orm.default_entity_manager'
           - AppBundle\Entity\Page

     app.managers.product_category_manager:
        class: AppBundle\Managers\ProductCategoryManager
        public: true
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - AppBundle\Entity\ProductCategory

     app.pagerfanta.template_default:
        class: AppBundle\Pagerfanta\DefaultView
        public: false
        tags: [{ name: 'pagerfanta.view', alias: 'app_pagerfanta_template_default'}]

     app.managers.product_attribute_manager:
        class: AppBundle\Managers\ProductAttrManager
        public: true
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - AppBundle\Entity\ProductAttr
            - '@app.managers.product_category_manager'
            - '@app.managers.product_attribute_value_manager'

     app.managers.product_attribute_value_manager:
        class: AppBundle\Managers\ProductAttrValueManager
        public: true
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - AppBundle\Entity\ProductAttrValue
            - '@app.managers.product_category_manager'

     app.model.filter.filter:
        class: AppBundle\Model\Filter\Filter
        public: false

     app.managers.product_manager:
        class: AppBundle\Managers\ProductManager
        public: true
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - AppBundle\Entity\Product
            - '@app.managers.product_category_manager'
            - '@app.managers.product_attribute_value_manager'
            - '@app.model.filter.filter'
            - '@form.factory'
            - 20

     app.form_filter.filter_type:
        class: AppBundle\Form\Filter\FilterType
#        arguments:
        tags:
           - { name: form.type }