parameters:

services:
     app.twig_extension:
        class: AppBundle\Twig\TwigExtension
        public: false
        arguments:
            - '@service_container'
        tags: [{ name: twig.extension }]

     twig.extension.sortbyfield:
        class: Snilius\Twig\SortByFieldExtension
        tags:
           - { name: twig.extension }

     app.product_manager:
        class: AppBundle\Managers\ProductManager
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - AppBundle\Entity\Product
            - 20

     app.product_category_manager:
        class: AppBundle\Managers\ProductCategoryManager
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - AppBundle\Entity\ProductCategory

     app.pagerfanta.template_default:
        class: AppBundle\Pagerfanta\DefaultView
        public: false
        tags: [{ name: 'pagerfanta.view', alias: 'app_pagerfanta_template_default'}]
