parameters:
   sonata.media.admin.groupname: Content

services:
    gedmo.listener.tree:
        class: Gedmo\Tree\TreeListener
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]

    sonata.admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, AppBundle\Controller\Admin\UserCRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Administration', label: 'Users', icon: '<i class="fa fa-cogs"></i>'}
        public: true

    sonata.admin.page:
        class: AppBundle\Admin\PageAdmin
        arguments: [~, AppBundle\Entity\Page, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Content, label: Pages, icon: '<i class="fa fa-th"></i>'}
        public: true


    sonata.admin.product:
        class: AppBundle\Admin\ProductAdmin
        arguments: [~, AppBundle\Entity\Product, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, group: E-Commerce, label: Products}
        public: true

    sonata.admin.product_category:
        class: AppBundle\Admin\ProductCategoryAdmin
        arguments: [~, AppBundle\Entity\ProductCategory, AppBundle\Controller\Admin\ProductCategoryCRUDController, 'title']
        tags:
            - {name: sonata.admin, manager_type: orm, group: E-Commerce, label: Category, icon: '<i class="fa fa-dollar"></i>'}
        public: true

    sonata.admin.product_attr:
        class: AppBundle\Admin\ProductAttrAdmin
        arguments: [~, AppBundle\Entity\ProductAttr, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, group: E-Commerce, label: 'Product Attributes'}
        public: true

    sonata.admin.product_attr_value:
        class: AppBundle\Admin\ProductAttrValueAdmin
        arguments: [~, AppBundle\Entity\ProductAttrValue, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, group: E-Commerce, label: 'Product Attribute Values'}
        public: true