AppBundle\Entity\User:
    properties:
        username:
            - NotBlank:
            - Length:
                max: 180
        email:
            - Email:
            - NotBlank:
            - Length:
                max: 180
#
AppBundle\Entity\Page:
    properties:
        title:
            - NotBlank:
            - Length:
                max: 255
        seoTitle:
            - Length:
                max: 255
        seoKeywords:
            - Length:
                max: 255
        seoDescription:
            - Length:
                max: 512
        description:
            - Length:
                max: 1024
#
AppBundle\Entity\ProductCategory:
    properties:
        title:
           - NotBlank:
           - Length:
               max: 255

AppBundle\Entity\Product:
    properties:
        title:
            - NotBlank:
            - Length:
                max: 255
        seoTitle:
            - Length:
                max: 255
        seoKeywords:
            - Length:
                max: 255
        seoDescription:
            - Length:
                max: 512
        description:
            - Length:
                max: 1024
        price:
            - NotBlank:
#
AppBundle\Entity\ProductAtt:
    properties:
        title:
            - NotBlank:
            - Length:
                max: 255