AppBundle\Entity\ProductAttr:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ProductAttrRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        type:
            type: smallint
            options:
                default: 1
        position:
            type: integer
            nullable: false;
            gedmo:
                - sortablePosition
    manyToMany:
        categories:
            targetEntity: AppBundle\Entity\ProductCategory
            inversedBy: products
            orderBy:
                lft: ASC
    oneToMany:
        values:
            targetEntity: AppBundle\Entity\ProductAttrValue
            mappedBy: attribute
    lifecycleCallbacks: {  }
