AppBundle\Entity\ProductCategory:
      type: entity
      repositoryClass: AppBundle\Repository\ProductCategoryRepository
      table: product_category
      gedmo:
          tree:
            type: nested
      indexes:
          title:
              columns: [ title ]
      id:
          id:
              type: integer
              id: true
              generator:
                  strategy: AUTO
      fields:
          title:
              type: string
              length: 255
          lft:
              type: integer
              gedmo:
                - treeLeft
          rgt:
              type: integer
              gedmo:
                - treeRight
          lvl:
              type: integer
              gedmo:
                - treeLevel
          parentId:
              type: integer
              nullable: true
          treeRoot:
              type: integer
              nullable: true
      manyToOne:
          root:
            targetEntity: AppBundle\Entity\ProductCategory
            joinColumn:
                name: tree_root
                referencedColumnName: id
                onDelete: CASCADE
            gedmo:
              - treeRoot
          parent:
            targetEntity: AppBundle\Entity\ProductCategory
            inversedBy: children
            joinColumn:
                name: parent_id
                referencedColumnName: id
                onDelete: CASCADE
            gedmo:
              - treeParent
      oneToMany:
          children:
              targetEntity: AppBundle\Entity\ProductCategory
              mappedBy: parent
              orderBy:
                  lft: ASC
      manyToMany:
          products:
              targetEntity: AppBundle\Entity\Product
              mappedBy: categories