AppBundle\Entity\ProductAttrValue:
    constraints:
        - Callback: validateValue
    properties:
        product:
            - NotNull:
            - NotBlank:
        attribute:
            - NotNull:
            - NotBlank:
